### ISSUE TITLE
Server crashes when solving puzzle

### ISSUE THREAD

**Issue by rhys-saldanha** [YUNG-GANG/YUNGs-Better-Desert-Temples#15] opened 2022-12-14 19:33 UTC
I've raised an issue against the FTB modpack I'm running: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2324

Please see the above issue for more details and a link to the error log. In short, whenever I solve one of the 3 puzzles in the first layer of the pyramid, the server crashes!

**Comment by yungnickyoung** [comment] 2022-12-14 19:38
Seems to be a duplicate of #14 , which in turn is caused by https://github.com/JoeFoxe/Hexerei-1.18/issues/68

**Comment by Gbergz** [comment] 2023-02-22 09:05
Still an issue.

**Closed as not planned** 2023-07-16 09:48 UTC
